using System.Collections.Generic;

namespace bagpipe {
  static class KnownSettings {
    public class SettingsData {
      public int ID { get; }
      public string Name { get; }
      public SettingsDataType Type { get; }

      public SettingsData(int ID, string Name, SettingsDataType Type) {
        this.ID = ID;
        this.Name = Name;
        this.Type = Type;
      }
    }

    public static readonly IReadOnlyDictionary<Game, IReadOnlyDictionary<int, SettingsData>> Data = new Dictionary<Game, IReadOnlyDictionary<int, SettingsData>>() {
      { Game.BL1, new Dictionary<int, SettingsData>() {
        { 2, new SettingsData(2, "InvertLook", SettingsDataType.Int32) },
        { 16, new SettingsData(16, "AutoAim", SettingsDataType.Int32) },
        { 26, new SettingsData(26, "VersionNumber", SettingsDataType.Int32) },
        { 27, new SettingsData(27, "WriteCount", SettingsDataType.Int32) },
        { 101, new SettingsData(101, "MasterVolume", SettingsDataType.Int32) },
        { 102, new SettingsData(102, "ControllerSensitivityX", SettingsDataType.Int32) },
        { 103, new SettingsData(103, "ControllerSensitivityY", SettingsDataType.Int32) },
        { 104, new SettingsData(104, "ViewAccel", SettingsDataType.Int32) },
        { 105, new SettingsData(105, "LastGameSpyUsername", SettingsDataType.String) },
        { 106, new SettingsData(106, "LastGameSpyPassword", SettingsDataType.String) },
        { 107, new SettingsData(107, "MusicVolume", SettingsDataType.Int32) },
        { 108, new SettingsData(108, "SFXVolume", SettingsDataType.Int32) },
        { 109, new SettingsData(109, "AcceptDuels", SettingsDataType.Int32) },
        { 110, new SettingsData(110, "AcceptTrades", SettingsDataType.Int32) },
        { 111, new SettingsData(111, "EnableSubtitles", SettingsDataType.Int32) },
        { 112, new SettingsData(112, "Brightness", SettingsDataType.Int32) },
        { 113, new SettingsData(113, "SnapToTarget", SettingsDataType.Int32) },
        { 114, new SettingsData(114, "HasUnlockedViralAchievement", SettingsDataType.Int32) },
        { 115, new SettingsData(115, "ControllerPreset", SettingsDataType.String) },
        { 116, new SettingsData(116, "LastSavedId", SettingsDataType.Int32) },
        { 117, new SettingsData(117, "DisableOptionalVO", SettingsDataType.Int32) },
        { 118, new SettingsData(118, "DisableTrainingMessages", SettingsDataType.Int32) },
        { 119, new SettingsData(119, "AmbientOcclusion", SettingsDataType.Int32) },
        { 120, new SettingsData(120, "ShadowQuality", SettingsDataType.Int32) },
        { 121, new SettingsData(121, "MouseSensitivity", SettingsDataType.Int32) },
        { 122, new SettingsData(122, "DlcNotifications", SettingsDataType.Int32) },
        { 123, new SettingsData(123, "AutoLogin", SettingsDataType.Int32) },
        { 124, new SettingsData(124, "VoiceVolume", SettingsDataType.Int32) },
        { 125, new SettingsData(125, "EnableLocalVoice", SettingsDataType.Int32) },
      } },
      { Game.BL1E, new Dictionary<int, SettingsData>() {
        { 2, new SettingsData(2, "InvertLook", SettingsDataType.Int32) },
        { 16, new SettingsData(16, "AutoAim", SettingsDataType.Int32) },
        { 26, new SettingsData(26, "VersionNumber", SettingsDataType.Int32) },
        { 27, new SettingsData(27, "WriteCount", SettingsDataType.Int32) },
        { 101, new SettingsData(101, "MasterVolume", SettingsDataType.Int32) },
        { 102, new SettingsData(102, "ControllerSensitivityX", SettingsDataType.Int32) },
        { 103, new SettingsData(103, "ControllerSensitivityY", SettingsDataType.Int32) },
        { 104, new SettingsData(104, "ViewAccel", SettingsDataType.Int32) },
        { 105, new SettingsData(105, "LastGameSpyUsername", SettingsDataType.String) },
        { 106, new SettingsData(106, "LastGameSpyPassword", SettingsDataType.String) },
        { 107, new SettingsData(107, "MusicVolume", SettingsDataType.Int32) },
        { 108, new SettingsData(108, "SFXVolume", SettingsDataType.Int32) },
        { 109, new SettingsData(109, "AcceptDuels", SettingsDataType.Int32) },
        { 110, new SettingsData(110, "AcceptTrades", SettingsDataType.Int32) },
        { 111, new SettingsData(111, "EnableSubtitles", SettingsDataType.Int32) },
        { 112, new SettingsData(112, "Brightness", SettingsDataType.Int32) },
        { 113, new SettingsData(113, "SnapToTarget", SettingsDataType.Int32) },
        { 114, new SettingsData(114, "HasUnlockedViralAchievement", SettingsDataType.Int32) },
        { 115, new SettingsData(115, "ControllerPreset", SettingsDataType.String) },
        { 116, new SettingsData(116, "LastSavedId", SettingsDataType.Int32) },
        { 117, new SettingsData(117, "DisableOptionalVO", SettingsDataType.Int32) },
        { 118, new SettingsData(118, "DisableTrainingMessages", SettingsDataType.Int32) },
        { 119, new SettingsData(119, "AmbientOcclusion", SettingsDataType.Int32) },
        { 120, new SettingsData(120, "ShadowQuality", SettingsDataType.Int32) },
        { 121, new SettingsData(121, "MouseSensitivity", SettingsDataType.Int32) },
        { 122, new SettingsData(122, "DlcNotifications", SettingsDataType.Int32) },
        { 123, new SettingsData(123, "AutoLogin", SettingsDataType.Int32) },
        { 125, new SettingsData(125, "EnableLocalVoice", SettingsDataType.Int32) },
        { 126, new SettingsData(126, "ShowCompass", SettingsDataType.Int32) },
        { 127, new SettingsData(127, "ShowMinimap", SettingsDataType.Int32) },
        { 128, new SettingsData(128, "HDR", SettingsDataType.Int32) },
        { 129, new SettingsData(129, "FOV", SettingsDataType.Int32) },
        { 130, new SettingsData(130, "keyCount", SettingsDataType.Int32) },
        { 131, new SettingsData(131, "keysSpent", SettingsDataType.Int32) },
        { 132, new SettingsData(132, "EulaAccepted", SettingsDataType.Int32) },
        { 134, new SettingsData(134, "ShotsFired", SettingsDataType.Int32) },
        { 135, new SettingsData(135, "TotalKills", SettingsDataType.Int32) },
        { 136, new SettingsData(136, "MaxLevel", SettingsDataType.Int32) },
        { 137, new SettingsData(137, "TotalItemsFound", SettingsDataType.Int32) },
        { 138, new SettingsData(138, "LegendaryItemsFound", SettingsDataType.Int32) },
        { 139, new SettingsData(139, "MouseSmoothing", SettingsDataType.Int32) },
        { 140, new SettingsData(140, "MouseAcceleration", SettingsDataType.Int32) },
        { 141, new SettingsData(141, "UseGamepad", SettingsDataType.Int32) },
        { 142, new SettingsData(142, "PauseGameOnFocusLoss", SettingsDataType.Int32) },
        { 143, new SettingsData(143, "VoiceOverVolume", SettingsDataType.Int32) },
        { 144, new SettingsData(144, "MuteAudioOnFocusLoss", SettingsDataType.Int32) },
        { 145, new SettingsData(145, "DisableWindowsKey", SettingsDataType.Int32) },
        { 146, new SettingsData(146, "ScopedMouseSensitivity", SettingsDataType.Int32) },
        { 147, new SettingsData(147, "MouseSensitivityVertical", SettingsDataType.Int32) },
        { 148, new SettingsData(148, "ScopedMouseSensitivityVertical", SettingsDataType.Int32) },
        { 149, new SettingsData(149, "SplitScreenHorizontal", SettingsDataType.Int32) },
        { 150, new SettingsData(150, "DisableLauncher", SettingsDataType.Int32) },
        { 151, new SettingsData(151, "CustomGamepadBindings", SettingsDataType.String) },
        { 152, new SettingsData(152, "SplitscreenFavorLeft", SettingsDataType.Int32) },
        { 153, new SettingsData(153, "SplitscreenFavorTop", SettingsDataType.Int32) },
        { 154, new SettingsData(154, "DynamicRange", SettingsDataType.Int32) },
        { 155, new SettingsData(155, "FramerateMode", SettingsDataType.Int32) },
        { 156, new SettingsData(156, "AutoEquipWeapon", SettingsDataType.Int32) },
        { 157, new SettingsData(157, "LobbyNetMode", SettingsDataType.String) },
        { 158, new SettingsData(158, "NewCharacterEntitlements", SettingsDataType.String) },
        { 159, new SettingsData(159, "MinimapShouldRotate", SettingsDataType.Int32) },
      } },
      { Game.BL2, new Dictionary<int, SettingsData>() {
        { 2, new SettingsData(2, "InvertGamepadLook", SettingsDataType.Int32) },
        { 16, new SettingsData(16, "AutoAim", SettingsDataType.Int32) },
        { 26, new SettingsData(26, "VersionNumber", SettingsDataType.Int32) },
        { 27, new SettingsData(27, "WriteCount", SettingsDataType.Int32) },
        { 101, new SettingsData(101, "MasterVolume", SettingsDataType.Int32) },
        { 102, new SettingsData(102, "ControllerSensitivityX", SettingsDataType.Int32) },
        { 103, new SettingsData(103, "ControllerSensitivityY", SettingsDataType.Int32) },
        { 104, new SettingsData(104, "ViewAccel", SettingsDataType.Int32) },
        { 105, new SettingsData(105, "InvertMouseLook", SettingsDataType.Int32) },
        { 106, new SettingsData(106, "IntroMovieViewed", SettingsDataType.Int32) },
        { 107, new SettingsData(107, "MusicVolume", SettingsDataType.Int32) },
        { 108, new SettingsData(108, "SFXVolume", SettingsDataType.Int32) },
        { 109, new SettingsData(109, "AcceptDuels", SettingsDataType.Int32) },
        { 110, new SettingsData(110, "AcceptTrades", SettingsDataType.Int32) },
        { 111, new SettingsData(111, "EnableSubtitles", SettingsDataType.Int32) },
        { 112, new SettingsData(112, "Brightness", SettingsDataType.Int32) },
        { 113, new SettingsData(113, "AutoAim", SettingsDataType.Int32) },
        { 114, new SettingsData(114, "HasUnlockedViralAchievement", SettingsDataType.Int32) },
        { 115, new SettingsData(115, "ControllerPreset", SettingsDataType.String) },
        { 116, new SettingsData(116, "LastSavedId", SettingsDataType.Int32) },
        { 117, new SettingsData(117, "DisableOptionalVO", SettingsDataType.Int32) },
        { 118, new SettingsData(118, "DisableTrainingMessages", SettingsDataType.Int32) },
        { 119, new SettingsData(119, "AmbientOcclusion", SettingsDataType.Int32) },
        { 120, new SettingsData(120, "HUDScaleE", SettingsDataType.Int32) },
        { 121, new SettingsData(121, "MouseSensitivity", SettingsDataType.Int32) },
        { 122, new SettingsData(122, "DlcNotifications", SettingsDataType.Int32) },
        { 124, new SettingsData(124, "VoiceVolume", SettingsDataType.Int32) },
        { 125, new SettingsData(125, "PushToTalk", SettingsDataType.Int32) },
        { 127, new SettingsData(127, "VOVolume", SettingsDataType.Int32) },
        { 128, new SettingsData(128, "PerShotForceFeedback", SettingsDataType.Int32) },
        { 129, new SettingsData(129, "PlayerFOV", SettingsDataType.Int32) },
        { 130, new SettingsData(130, "StashSlot0", SettingsDataType.Blob) },
        { 131, new SettingsData(131, "StashSlot1", SettingsDataType.Blob) },
        { 132, new SettingsData(132, "StashSlot2", SettingsDataType.Blob) },
        { 133, new SettingsData(133, "StashSlot3", SettingsDataType.Blob) },
        { 134, new SettingsData(134, "CrouchToggle", SettingsDataType.Int32) },
        { 135, new SettingsData(135, "ZoomToggle", SettingsDataType.Int32) },
        { 136, new SettingsData(136, "BadassPoints", SettingsDataType.Int32) },
        { 137, new SettingsData(137, "BadassPointsSpent", SettingsDataType.Int32) },
        { 138, new SettingsData(138, "BadassTokens", SettingsDataType.Int32) },
        { 139, new SettingsData(139, "BadassTokensEarned", SettingsDataType.Int32) },
        { 140, new SettingsData(140, "AbsoluteMinimap", SettingsDataType.Int32) },
        { 141, new SettingsData(141, "HUDScaleX", SettingsDataType.Int32) },
        { 142, new SettingsData(142, "HUDScaleY", SettingsDataType.Int32) },
        { 143, new SettingsData(143, "BadassRewardsEarned", SettingsDataType.String) },
        { 145, new SettingsData(145, "DriftCameraLock", SettingsDataType.Int32) },
        { 147, new SettingsData(147, "SplitDirection", SettingsDataType.Int32) },
        { 148, new SettingsData(148, "TradingDisabled", SettingsDataType.Int32) },
        { 149, new SettingsData(149, "KeyRebinding", SettingsDataType.String) },
        { 150, new SettingsData(150, "CheckedForPreviousGame", SettingsDataType.Int32) },
        { 151, new SettingsData(151, "LastNewOfferVersion", SettingsDataType.Int32) },
        { 152, new SettingsData(152, "MouseSmoothing", SettingsDataType.Int32) },
        { 153, new SettingsData(153, "ItemRotationNew", SettingsDataType.Int32) },
        { 154, new SettingsData(154, "GamepadInvertTurn", SettingsDataType.Byte) },
        { 155, new SettingsData(155, "GamepadInvertMove", SettingsDataType.Byte) },
        { 156, new SettingsData(156, "GamepadInvertStrafe", SettingsDataType.Byte) },
        { 157, new SettingsData(157, "ShouldCensorContent", SettingsDataType.Int32) },
        { 158, new SettingsData(158, "ControllerRebinding", SettingsDataType.String) },
        { 159, new SettingsData(159, "GunzerkingAutoSwitch", SettingsDataType.Byte) },
        { 160, new SettingsData(160, "EasterEggOption", SettingsDataType.Byte) },
        { 161, new SettingsData(161, "RewardedForPlayingPreviousGame", SettingsDataType.Int32) },
        { 162, new SettingsData(162, "GoldenKeysEarned", SettingsDataType.Blob) },
        { 163, new SettingsData(163, "DisableUISway", SettingsDataType.Byte) },
        { 164, new SettingsData(164, "BadassRewardsToOfferNext", SettingsDataType.String) },
        { 165, new SettingsData(165, "InvertedReverseSteering", SettingsDataType.Byte) },
        { 166, new SettingsData(166, "BackpackSortPreference", SettingsDataType.Int32) },
        { 167, new SettingsData(167, "MouseAutoAim", SettingsDataType.Int32) },
        { 169, new SettingsData(169, "OakUpsellViewed", SettingsDataType.Empty) },
        { 300, new SettingsData(300, "UnlockedCustomizations_MainGame", SettingsDataType.Blob) },
      } },
      { Game.TPS, new Dictionary<int, SettingsData>() {
        { 2, new SettingsData(2, "InvertGamepadLook", SettingsDataType.Int32) },
        { 16, new SettingsData(16, "AutoAim", SettingsDataType.Int32) },
        { 26, new SettingsData(26, "VersionNumber", SettingsDataType.Int32) },
        { 27, new SettingsData(27, "WriteCount", SettingsDataType.Int32) },
        { 101, new SettingsData(101, "MasterVolume", SettingsDataType.Int32) },
        { 102, new SettingsData(102, "ControllerSensitivityX", SettingsDataType.Int32) },
        { 103, new SettingsData(103, "ControllerSensitivityY", SettingsDataType.Int32) },
        { 104, new SettingsData(104, "ViewAccel", SettingsDataType.Int32) },
        { 105, new SettingsData(105, "InvertMouseLook", SettingsDataType.Int32) },
        { 106, new SettingsData(106, "IntroMovieViewed", SettingsDataType.Int32) },
        { 107, new SettingsData(107, "MusicVolume", SettingsDataType.Int32) },
        { 108, new SettingsData(108, "SFXVolume", SettingsDataType.Int32) },
        { 109, new SettingsData(109, "AcceptDuels", SettingsDataType.Int32) },
        { 110, new SettingsData(110, "AcceptTrades", SettingsDataType.Int32) },
        { 111, new SettingsData(111, "EnableSubtitles", SettingsDataType.Int32) },
        { 112, new SettingsData(112, "Brightness", SettingsDataType.Int32) },
        { 113, new SettingsData(113, "AutoAim", SettingsDataType.Int32) },
        { 114, new SettingsData(114, "HasUnlockedViralAchievement", SettingsDataType.Int32) },
        { 115, new SettingsData(115, "ControllerPreset", SettingsDataType.String) },
        { 116, new SettingsData(116, "LastSavedId", SettingsDataType.Int32) },
        { 117, new SettingsData(117, "DisableOptionalVO", SettingsDataType.Int32) },
        { 118, new SettingsData(118, "DisableTrainingMessages", SettingsDataType.Int32) },
        { 119, new SettingsData(119, "AmbientOcclusion", SettingsDataType.Int32) },
        { 120, new SettingsData(120, "HUDScaleE", SettingsDataType.Int32) },
        { 121, new SettingsData(121, "MouseSensitivity", SettingsDataType.Int32) },
        { 122, new SettingsData(122, "DlcNotifications", SettingsDataType.Int32) },
        { 124, new SettingsData(124, "VoiceVolume", SettingsDataType.Int32) },
        { 125, new SettingsData(125, "PushToTalk", SettingsDataType.Int32) },
        { 127, new SettingsData(127, "VOVolume", SettingsDataType.Int32) },
        { 128, new SettingsData(128, "PerShotForceFeedback", SettingsDataType.Int32) },
        { 129, new SettingsData(129, "PlayerFOV", SettingsDataType.Int32) },
        { 130, new SettingsData(130, "StashSlot0", SettingsDataType.Blob) },
        { 131, new SettingsData(131, "StashSlot1", SettingsDataType.Blob) },
        { 132, new SettingsData(132, "StashSlot2", SettingsDataType.Blob) },
        { 133, new SettingsData(133, "StashSlot3", SettingsDataType.Blob) },
        { 134, new SettingsData(134, "CrouchToggle", SettingsDataType.Int32) },
        { 135, new SettingsData(135, "ZoomToggle", SettingsDataType.Int32) },
        { 136, new SettingsData(136, "BadassPoints", SettingsDataType.Int32) },
        { 137, new SettingsData(137, "BadassPointsSpent", SettingsDataType.Int32) },
        { 138, new SettingsData(138, "BadassTokens", SettingsDataType.Int32) },
        { 139, new SettingsData(139, "BadassTokensEarned", SettingsDataType.Int32) },
        { 140, new SettingsData(140, "AbsoluteMinimap", SettingsDataType.Int32) },
        { 141, new SettingsData(141, "HUDScaleX", SettingsDataType.Int32) },
        { 142, new SettingsData(142, "HUDScaleY", SettingsDataType.Int32) },
        { 143, new SettingsData(143, "BadassRewardsEarned", SettingsDataType.String) },
        { 145, new SettingsData(145, "DriftCameraLock", SettingsDataType.Int32) },
        { 147, new SettingsData(147, "SplitDirection", SettingsDataType.Int32) },
        { 148, new SettingsData(148, "TradingDisabled", SettingsDataType.Int32) },
        { 149, new SettingsData(149, "KeyRebinding", SettingsDataType.String) },
        { 150, new SettingsData(150, "CheckedForPreviousGame", SettingsDataType.Int32) },
        { 151, new SettingsData(151, "LastNewOfferVersion", SettingsDataType.Int32) },
        { 152, new SettingsData(152, "MouseSmoothing", SettingsDataType.Int32) },
        { 153, new SettingsData(153, "ItemRotationNew", SettingsDataType.Int32) },
        { 154, new SettingsData(154, "GamepadInvertTurn", SettingsDataType.Byte) },
        { 155, new SettingsData(155, "GamepadInvertMove", SettingsDataType.Byte) },
        { 156, new SettingsData(156, "GamepadInvertStrafe", SettingsDataType.Byte) },
        { 157, new SettingsData(157, "ShouldCensorContent", SettingsDataType.Byte) },
        { 158, new SettingsData(158, "ControllerRebinding", SettingsDataType.String) },
        { 159, new SettingsData(159, "GunzerkingAutoSwitch", SettingsDataType.Byte) },
        { 160, new SettingsData(160, "EasterEggOption", SettingsDataType.Byte) },
        { 161, new SettingsData(161, "RewardedForPlayingPreviousGame", SettingsDataType.Int32) },
        { 162, new SettingsData(162, "GoldenKeysEarned", SettingsDataType.Blob) },
        { 163, new SettingsData(163, "DisableUISway", SettingsDataType.Byte) },
        { 164, new SettingsData(164, "BadassRewardsToOfferNext", SettingsDataType.String) },
        { 165, new SettingsData(165, "InvertedReverseSteering", SettingsDataType.Byte) },
        { 166, new SettingsData(166, "BackpackSortPreference", SettingsDataType.Int32) },
        { 167, new SettingsData(167, "MoonstoneRewardEarned", SettingsDataType.Int32) },
        { 168, new SettingsData(168, "ResetCameraOnSlam", SettingsDataType.Int32) },
        { 169, new SettingsData(169, "MouseAutoAim", SettingsDataType.Int32) },
        { 171, new SettingsData(171, "ItemRewardEarnedForBL1", SettingsDataType.Int32) },
        { 172, new SettingsData(172, "ItemRewardEarnedForBL2", SettingsDataType.Int32) },
        { 173, new SettingsData(173, "BadassRankChanged", SettingsDataType.Int32) },
        { 174, new SettingsData(174, "OpenedShiftGifts", SettingsDataType.String) },
        { 175, new SettingsData(175, "OptInShiftEvents", SettingsDataType.Int32) },
        { 176, new SettingsData(176, "BadassPointsRewardEarned", SettingsDataType.Int32) },
        { 178, new SettingsData(178, "OakUpsellViewed", SettingsDataType.Empty) },
        { 300, new SettingsData(300, "UnlockedCustomizations_MainGame", SettingsDataType.Blob) },
      } },
    };

  }
}
